from typing import Any, Iterable, Iterator, List, Mapping, Protocol, Tuple

from werkzeug.wrappers import Response

class _HeaderMapping(Protocol):
    def items(self) -> Iterable[tuple[str, str]]: ...

class _ArgsMapping(Protocol):
    def items(self) -> Iterable[tuple[str, str]]: ...

class Request(Protocol):
    headers: _HeaderMapping
    args: _ArgsMapping
    path: str
    method: str
    def get_data(self, *, as_text: bool = ...) -> str: ...

class RequestHandler:
    def respond_with_json(self, obj: Any, *, status: int = ..., headers: Mapping[str, str] | None = ...) -> None: ...
    def respond_with_response(self, response: Response, **kwargs: Any) -> None: ...

class HTTPServer:
    log: List[Tuple[Request, Response]]
    def expect_request(self, *args: Any, ordered: bool = ..., **kwargs: Any) -> RequestHandler: ...
    def expect_ordered_request(self, *args: Any, **kwargs: Any) -> RequestHandler: ...
    def url_for(self, path: str) -> str: ...

def httpserver_listen_address() -> tuple[str, int]: ...
def make_httpserver(httpserver_listen_address: tuple[str, int], httpserver_ssl_context: Any) -> Iterator[HTTPServer]: ...
def httpserver() -> HTTPServer: ...
def make_httpserver_ipv4(httpserver_ssl_context: Any) -> Iterator[HTTPServer]: ...
def httpserver_ipv4() -> HTTPServer: ...
def make_httpserver_ipv6(httpserver_ssl_context: Any) -> Iterator[HTTPServer]: ...
def httpserver_ipv6() -> HTTPServer: ...
