services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 1-3.13-bullseye

    volumes:
      - ..:/workspace:cached # Mount the whole workspace read-write
      - vscode_extensions_data:/root/.vscode-server/data/User/globalStorage:cached # Persist VS Code extension data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for act

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Commented out the env file so it does not crash the container build, if not present
    #env_file:
    #  - ../.env

    depends_on:
      - qdrant

  docs:
    build:
      context: ..
      dockerfile: docs/Dockerfile

    volumes:
      - ..:/workspace:cached # Mount the whole workspace read-write

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use root user for consistency with the app service and Sphinx build steps
    user: root

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ../data/qdrant:/qdrant/storage:cached
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  vscode_extensions_data:
