name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - 'docs/**'
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/docs/') || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies (including docs)
        run: |
          poetry install --no-interaction --no-root --with docs

      - name: Build Sphinx documentation
        run: |
          poetry run sphinx-build -b html docs/source docs/build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
          force_orphan: true